logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG
jwt:
  header: Authorization
  secret: "secret"
  expiration: 604800
  tokenHead: "Bearer "
  exceptUrl: "/**"
# mybatis 分页插件
pagehelper:
    helperDialect: mysql                           #分页插件方言选择
    reasonable: true                               #合理化参数，设为true时pageNum<=0 时会查第一页， pageNum>pages（超过总数时），会查询最后一页
    supportMethodsArguments: true
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379  # Redis服务器连接端口
  #    password: 285414 # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8   # 连接池中的最大空闲连接
        min-idle: 0   # 连接池中的最小空闲连接
    timeout: 5000
#    cache:
#      redis:
#       time-to-live: 30000