logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG
jwt:
  header: Authorization
  secret: "secret"
  expiration: 604800
  tokenHead: "Bearer "
  exceptUrl: "/**"
# mybatis 分页插件
pagehelper:
    helperDialect: mysql                           #分页插件方言选择
    reasonable: true                               #合理化参数，设为true时pageNum<=0 时会查第一页， pageNum>pages（超过总数时），会查询最后一页
    supportMethodsArguments: true
